### ISSUE TITLE
Support -moz-, -ms, -o prefix

### ISSUE THREAD

**Issue by yisibl** [hallvors/postcss-flexboxfixer#3]
``` css
.foo {
  display: -moz-box;
  display: -ms-flexbox;
}
```

**Comment by hallvors** [comment]
I'd guess that a CSS file that has -moz- and/or -ms- syntax for flexbox but _not_ -webkit- is fairly rare. This means two things:

1) Handling just -webkit- lets us add the standards-compatible syntax to most CSS files out there
2) If we implement support for the other ones, we also need some logic for which one to prioritise - what if the rules are different?

Hence I think adding this is somewhat complicated and the gain seems rather small.

**Comment by yisibl** [comment]
Thank you for your reply. There are two main reasons.

1) as a plugin needs to have a sound feature, in particular, [postcss-unprefix](https://github.com/yisibl/postcss-unprefix) relies on this plugin.
2) we need to deal with -moz/-ms and not just because some developers write them, because most of the time we need to test the compatibility of a specific browser, this time we just write a prefix, and then automatically generated by autoprefixer and postcss-flexboxfixer.

The others asked @ai  to help supplement.

**Comment by hallvors** [comment]
I will of course consider pull requests if you or @ai finds this feature important.
Personally, I will unfortunately not be able to prioritise this now.

**Comment by gucong3000** [comment]
@yisibl 已经满足你的愿望了，现已支持所有私有属性前缀
