### ISSUE TITLE
eachDecl is deprecated

### ISSUE THREAD

**Issue by reitermarkus** [hallvors/postcss-flexboxfixer#6]
According to the warning generated:

```
Container#eachDecl is deprecated. Use Container#walkDecls instead.
```

**Comment by reitermarkus** [comment]
https://github.com/hallvors/postcss-flexboxfixer/issues/4.

**Comment by hallvors** [comment]
https://github.com/hallvors/postcss-flexboxfixer/commit/f1f2f1d1678ce042bee5be14d4acc2620b06b1bf
